CREATE TABLE payment(
  id VARCHAR(12) NOT NULL PRIMARY KEY,
  order_id VARCHAR(255) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(25) DEFAULT 'SUCCESS' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);